# version: "3.7"
# name: furniture-exchange

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bale
      POSTGRES_PASSWORD: bale
      POSTGRES_DB: FurnitureExchange
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    container_name: furniture-backend
    build:
      context: ./server
      dockerfile: Dockerfile.development
    ports:
      - ${PORT}:${PORT}
      - 3002:3002 # Websocket port
    environment:
      - PORT=${PORT}
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./server/.env.development
    depends_on:
      - redis
      - postgres
    expose:
      - 3001

  fe-user:
    container_name: "furniture-fe-user"
    build:
      context: ./client/user-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - backend

  fe-admin:
    container_name: furniture-fe-admin
    build:
      context: ./client/admin-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    expose:
      - 80

  nginx:
    container_name: furniture-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fe-admin

volumes:
  redis-data:
    name: redis-data
    driver: local
  postgres-data:
    name: postgres-data
    driver: local
