version: '3.7'
name: furniture-exchange

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bale
      POSTGRES_PASSWORD: bale
      POSTGRES_DB: FurnitureExchange
    # volumes:
    # - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    container_name: furniture-backend
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./.env.development
    depends_on:
      - redis
      - postgres

volumes:
  redis-data:
    driver: local
#   postgres-data:
#     driver: local
