pipeline {
    agent any

    stages {
        stage("Clone") {
            steps {
                git branch: "setup/cicd-backend",
                    url: "https://github.com/Ninehcobra-Bale-Bros/Furniture-Exchange.git"
            }
        }
    }
}