import { PartialType } from '@nestjs/mapped-types';
import { RevenueDto } from './revenue.dto';
import { ApiProperty } from '@nestjs/swagger';

export class CreateRevenueDto extends PartialType(RevenueDto) {
  @ApiProperty({
    required: true,
    type: 'number',
    description: 'Total revenue',
    example: '0',
  })
  total_revenue: number;

  @ApiProperty({
    required: true,
    type: 'number',
    description: 'Total sales generated by the seller',
    example: '0',
  })
  total_sales: number;
}
